apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vaultwarden-tls
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  secretName: vaultwarden-tls
  privateKeyRotationPolicy: Never
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - vault.129-80-246-47.nip.io
