---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vaultwarden-secrets
  namespace: vaultwarden
spec:
  encryptedData:
    ADMIN_TOKEN: AgAFJKPjAvsvJgKfbDS9Q0ldsDs4uNBzO/THjXKO6j54reWTWOAyp79yCyoeeGJg7LWITHjvCdiYMwfjzM48b4i3gu/FfGYujo+PElCp5JsnvFR3aGz+xZV6PcFL92fJEL2/itD2b9+ztc8org32Jg6jHUfm3a9DCS5LR4m5lAa/rsW9mlTllZ6xLrApnMvkzpzHR2T26pMF0aBhlGj/tDCaMgKc47bWYrB7reI44bCzqgskAFttOz2tO6PK6FbMzeAFwudZ7q6q2AfL5RmJ3d8pd2fJ8Z8CKpP4aUN7nemGJsfOTVoZahGfIhn4o9DjxEin/1MoIEIbDsnxWp90EtAkakzZ9XXAwY9D5W2huK0H+bJujzlRTD0BJH1xoG51+E/ViZDGvFhjHys2PWCt6bkLGz2dpNabUOg5UrvINxQ05ZmeXFsV0qEO0Dq7sLoxozuIhw8QIduRWNk/jPb0yCa0W5obk4uqGk96B7GBX1K2V49DxS9MWVB1F+RU3OwS3NjUUpEoxS4mm+dezcmIu909HqN9CVJCd+yepcelHGddcAP8zukc+W6HEmtyfch1Mn/LgBdO++/c3iIbv/R3Q6Oo/8KUDD9NqEtw3/SAEKklayoE4O6xvrJvpYTF+C7GtT9Rdo2MIXUN9kQNRPVronPeUvNUtnMhpkd4VAY/PTu37A7wPJqr4YB16aDvmBuIhDDsLEYRYrVCecMXUw3cIsFbMiYEfWc8czZzUa+WdSXuq6m1Aj6LxH/H8Du2b0zDBoshR6XBe46TGBi87rQbQ5Yr
  template:
    metadata:
      creationTimestamp: null
      name: vaultwarden-secrets
      namespace: vaultwarden
