---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: app-config
  namespace: ckad-apps
spec:
  encryptedData:
    API_KEY: AgBHHOfyOLeXjD7X3Ndd2Sek+6rYNRhWD1LXeepiwILgeAj40UP0CQJv5E5VnLjvBi+TKz7ZqiUj2hOYKast/9KtEpWRjauWGQrcRCsW8YMs0j/wKFY1YlY3PTbuEqKflUCJftVfIuCdTB0KUapMHeHd39PKayLIqpkxvOMwqypcaqZqFMrYU24BO98eg2yBIh44tVn3cbNIiSDkxjNcA0QNENP/gGIZvpUOgpX3toOjAO3pgQ61FfaPUm6mZzLt1ZsUMG19UpmCYx2Nbrb6cM6yZQus1YNEf5DaT565VwR/LTXl2SQCdge7sqSP1NB8MLPGfP1e67kOHjpQ+3CU0EVyc3QZelTjQeVIZvpiHCEv6tOLIHSAZDkNggYTh75tUfqUYPOMZzpMKs8VBStc7MT+hX+8iRFGN2HyCROBIwBmIjAfMi25A8gnoRGrYKLmIkIVmtyuAKucxNCMlM+ZcKKzUmtKdO71yeosEbYw2BfQX16BO8BCSgi4cpL6fISIHf7M2jcK1f+7QCC0hZ9iYobPruU2nJJqFkg1LwiRbtMXGDotzTo3fPaHVkhRVvmiL7n2Nr/bZvIZiGfkNSQV39BCG+/0yoTXfilkpwCRRO1vfaWIrA63e6z3q3EsXp884oDKCK3aMspF64mSQJrh2amZu2BS5exnB8I2+Hwi/0cwgfgbnBCtWRAB0D5cW216kj0m/sK8DfUP9O2lmELZaR1Ulp16Q6Onw3V0harU
  template:
    metadata:
      creationTimestamp: null
      name: app-config
      namespace: ckad-apps
