namespace: ckad-apps
replicaCount: 2

image:
  repository: registry.gitlab.com/oci-project/oci-applications/ckad-app
  tag: 35c695a4

service:
  port: 80
  targetPort: 8080

resources:
  requests:
    memory: "64Mi"
    cpu: "100m"
  limits:
    memory: "128Mi"
    cpu: "250m"

probes:
  readiness:
    path: /
    initialDelay: 5
  liveness:
    path: /health
    initialDelay: 10

networkPolicy:
  allowedLabelValue: granted